return {
	["*"] = {en = "* (generated)"},
	["aa"] = {en = "Afar"},
	["ab"] = {en = "Abkhazian", l = "Аԥсшәа"},
	["ace"] = {en = "Acehnese"},
	["ach"] = {en = "Acholi"},
	["ada"] = {en = "Adangme"},
	["ady"] = {en = "Adyghe"},
	["ae"] = {en = "Avestan"},
	["af"] = {en = "Afrikaans", l = "Afrikaans"},
	["afh"] = {en = "Afrihili"},
	["aii"] = {en = "Assyrian Neo-Aramaic"},
	["ain"] = {en = "Ainu (Japan)"},
	["ak"] = {en = "Akan"},
	["ale"] = {en = "Aleut"},
	["alt"] = {en = "Altai (Southern)"},
	["am"] = {en = "Amharic"},
	["an"] = {en = "Aragonese"},
	["ang"] = {en = "English (Old)"},
	["anp"] = {en = "Angika"},
	["apc"] = {en = "Arabic (Levantine)"},
	["ar"] = {en = "Arabic", l = "العربية"},
	["ar_BH"] = {en = "Arabic (Bahrain)"},
	["ar_DZ"] = {en = "Arabic (Algeria)"},
	["ar_EG"] = {en = "Arabic (Egypt)"},
	["ar_IQ"] = {en = "Arabic"},
	["ar_LY"] = {en = "Arabic (Libya)"},
	["ar_MA"] = {en = "Arabic (Morocco)"},
	["ar_SA"] = {en = "Arabic (Saudi Arabia)"},
	["ar_TN"] = {en = "Arabic"},
	["ar_XB"] = {en = "Arabic (XB pseudolocale)"},
	["ar_YE"] = {en = "Arabic (Yemen)"},
	["arn"] = {en = "Mapudungun"},
	["ars"] = {en = "Arabic (Najdi)"},
	["as"] = {en = "Assamese"},
	["ast"] = {en = "Asturian", l = "asturianu"},
	["av"] = {en = "Avaric"},
	["ay"] = {en = "Aymara"},
	["ayc"] = {en = "Aymara (Southern)"},
	["az"] = {en = "Azerbaijani", l = "Azərbaycanca"},
	["azb"] = {en = "Azerbaijani (Southern)"},
	["ba"] = {en = "Bashkir"},
	["ban"] = {en = "Balinese"},
	["bar"] = {en = "Bavarian"},
	["bas"] = {en = "Basa (Cameroon)"},
	["be"] = {en = "Belarusian", l = "Беларуская"},
	["be_Latn"] = {en = "Belarusian (latin)"},
	["bem"] = {en = "Bemba"},
	["ber"] = {en = "Berber", l = "ⵜⴰⵎⴰⵣⵉⵖⵜ"},
	["bez"] = {en = "Bena"},
	["bg"] = {en = "Bulgarian", l = "Български"},
	["bh"] = {en = "Bihari"},
	["bh_IN"] = {en = "Bihari"},
	["bho"] = {en = "Bhojpuri"},
	["bi"] = {en = "Bislama"},
	["biodentis"] = {en = "biodentis (generated)"},
	["bm"] = {en = "Bambara"},
	["bn"] = {en = "Bengali", l = "বাংলা"},
	["bn_BD"] = {en = "Bengali (Bangladesh)"},
	["bn_IN"] = {en = "Bengali (India)"},
	["bo"] = {en = "Tibetan", l = "བོད་སྐད་"},
	["bqi"] = {en = "Luri (Bakhtiari)"},
	["br"] = {en = "Breton", l = "Brezhoneg"},
	["brx"] = {en = "Bodo"},
	["bs"] = {en = "Bosnian"},
	["bs_Latn"] = {en = "Bosnian (latin)"},
	["bul_BG"] = {en = "Bulgarian"},
	["byn"] = {en = "Bilen"},
	["c1"] = {en = "c1 (generated)"},
	["c2"] = {en = "c2 (generated)"},
	["ca"] = {en = "Catalan", l = "català"},
	["ca@valencia"] = {en = "Valencian"},
	["ca_AD"] = {en = "Catalan (Andorra)"},
	["cadstar"] = {en = "cadstar (generated)"},
	["cak"] = {en = "Kaqchikel"},
	["cares"] = {en = "cares (generated)"},
	["ce"] = {en = "Chechen", l = "нохчийн"},
	["ceb"] = {en = "Cebuano"},
	["ch"] = {en = "Chamorro"},
	["chr"] = {en = "Cherokee"},
	["ckb"] = {en = "Kurdish (Central)"},
	["cnr"] = {en = "Montenegrin"},
	["co"] = {en = "Corsican"},
	["cpe"] = {en = "Creoles and pidgins (English based)"},
	["cpp"] = {en = "Creoles and pidgins (Portuguese-based)"},
	["cr"] = {en = "Cree"},
	["crh"] = {en = "Crimean Tatar"},
	["cs"] = {en = "Czech", l = "Čeština"},
	["cs_CARES"] = {en = "Czech"},
	["csb"] = {en = "Kashubian"},
	["cu"] = {en = "Slavonic (Old Church)"},
	["cv"] = {en = "Chuvash", l = "Чӑвашла"},
	["cy"] = {en = "Welsh", l = "Cymraeg"},
	["cz_CZ"] = {en = "Czech"},
	["da"] = {en = "Danish", l = "Dansk"},
	["de"] = {en = "German", l = "Deutsch"},
	["de@formal"] = {en = "German (formal)"},
	["de@informal"] = {en = "German (informal)"},
	["de_1901"] = {en = "German (old spelling)"},
	["de_ALM@x"] = {en = "German"},
	["de_AT"] = {en = "German (Austria)"},
	["de_CARES"] = {en = "German"},
	["de_CH"] = {en = "German (Switzerland)"},
	["de_DE@rude"] = {en = "German"},
	["de_DIVEO"] = {en = "German"},
	["de_FORMAL"] = {en = "German"},
	["de_LAVA"] = {en = "German"},
	["de_LU"] = {en = "German (Luxembourg)"},
	["de_STRAUMANN"] = {en = "German"},
	["de_V26"] = {en = "German"},
	["de_ZENO"] = {en = "German"},
	["de_ZH"] = {en = "German"},
	["de_ZUERICH-LERNT"] = {en = "German"},
	["defaultmessages"] = {en = "defaultmessages (generated)"},
	["del"] = {en = "Delaware"},
	["dev"] = {en = "dev (generated)"},
	["dnk"] = {en = "Dengka"},
	["doi"] = {en = "Dogri"},
	["dsb"] = {en = "Lower Sorbian"},
	["dua"] = {en = "Duala"},
	["dum"] = {en = "Dutch (Middle)"},
	["dv"] = {en = "Dhivehi"},
	["dwosle"] = {en = "dwosle (generated)"},
	["dz"] = {en = "Dzongkha"},
	["ee"] = {en = "Ewe"},
	["el"] = {en = "Greek", l = "Ελληνικά"},
	["en"] = {en = "English"},
	["en-Shaw"] = {en = "English (Shavian)"},
	["en@boldquot"] = {en = "English"},
	["en@pirate"] = {en = "English (Pirate)"},
	["en@quot"] = {en = "English"},
	["en@uwu"] = {en = "English"},
	["en_001"] = {en = "English"},
	["en_APPINFO"] = {en = "English"},
	["en_AU"] = {en = "English (Australia)"},
	["en_CA"] = {en = "English (Canada)"},
	["en_CH"] = {en = "English"},
	["en_GB"] = {en = "English (United Kingdom)"},
	["en_IE"] = {en = "English (Ireland)"},
	["en_IN"] = {en = "English (India)"},
	["en_NL"] = {en = "English"},
	["en_NZ"] = {en = "English (New Zealand)"},
	["en_PH"] = {en = "English (Philippines)"},
	["en_SHAW"] = {en = "English"},
	["en_Shaw"] = {en = "English (Shavian)"},
	["en_Shaw_GB"] = {en = "English (Shavian, United Kingdom)"},
	["en_UD"] = {en = "English"},
	["en_UK"] = {en = "English"},
	["en_US"] = {en = "English (United States)"},
	["en_US@rude"] = {en = "English (United States)"},
	["en_UWU@x"] = {en = "English"},
	["en_XA"] = {en = "English (XA pseudolocale)"},
	["en_XC"] = {en = "English"},
	["en_ZA"] = {en = "English (South Africa)"},
	["en_devel"] = {en = "English (Developer)"},
	["enm"] = {en = "English (Middle)"},
	["eo"] = {en = "Esperanto", l = "Esperanto"},
	["eo_UY"] = {en = "Esperanto"},
	["es"] = {en = "Spanish", l = "Español"},
	["es@formal"] = {en = "Spanish (formal)"},
	["es@informal"] = {en = "Spanish (informal)"},
	["es_419"] = {en = "Spanish (Latin America)"},
	["es_AR"] = {en = "Spanish (Argentina)"},
	["es_BO"] = {en = "Spanish (Bolivia)"},
	["es_CARES"] = {en = "Spanish"},
	["es_CL"] = {en = "Spanish (Chile)"},
	["es_CO"] = {en = "Spanish (Colombia)"},
	["es_CR"] = {en = "Spanish (Costa Rica)"},
	["es_DO"] = {en = "Spanish (Dominican Republic)"},
	["es_EC"] = {en = "Spanish (Ecuador)"},
	["es_GT"] = {en = "Spanish"},
	["es_HN"] = {en = "Spanish"},
	["es_LAVA"] = {en = "Spanish"},
	["es_MX"] = {en = "Spanish (Mexico)"},
	["es_NI"] = {en = "Spanish (Nicaragua)"},
	["es_PA"] = {en = "Spanish (Panama)"},
	["es_PE"] = {en = "Spanish (Peru)"},
	["es_PR"] = {en = "Spanish (Puerto Rico)"},
	["es_PY"] = {en = "Spanish"},
	["es_SV"] = {en = "Spanish (El Salvador)"},
	["es_US"] = {en = "Spanish (American)"},
	["es_UY"] = {en = "Spanish (Uruguay)"},
	["es_VE"] = {en = "Spanish (Venezuela)"},
	["esd"] = {en = "esd (generated)"},
	["et"] = {en = "Estonian", l = "eesti"},
	["eu"] = {en = "Basque", l = "euskara"},
	["euskera"] = {en = "euskera (generated)"},
	["ext"] = {en = "Extremaduran"},
	["fa"] = {en = "Persian", l = "فارسی"},
	["fa_AF"] = {en = "Dari"},
	["faq_URLS"] = {en = "faq_URLS (generated)"},
	["ff"] = {en = "Fulah"},
	["fi"] = {en = "Finnish", l = "Suomi"},
	["fil"] = {en = "Filipino", l = "Filipino"},
	["fil_PH"] = {en = "Filipino"},
	["fj"] = {en = "Fijian"},
	["fo"] = {en = "Faroese"},
	["fon"] = {en = "Fon"},
	["fr"] = {en = "French", l = "Français"},
	["fr@formal"] = {en = "French (formal)"},
	["fr@informal"] = {en = "French (informal)"},
	["fr_AG"] = {en = "French (Antigua and Barbuda)"},
	["fr_BE"] = {en = "French (Belgium)"},
	["fr_CA"] = {en = "French (Canada)"},
	["fr_CARES"] = {en = "French"},
	["fr_CH"] = {en = "French (Switzerland)"},
	["fr_LAVA"] = {en = "French"},
	["fr_LU"] = {en = "French (Luxembourg)"},
	["fr_STRAUMANN"] = {en = "French"},
	["fr_V26"] = {en = "French"},
	["frc"] = {en = "French (Louisiana)"},
	["frm"] = {en = "French (Middle)"},
	["fro"] = {en = "French (Old)"},
	["frp"] = {en = "Franco-Provençal"},
	["frs"] = {en = "Frisian (Eastern)"},
	["fur"] = {en = "Friulian", l = "furlan"},
	["fy"] = {en = "Frisian", l = "Frysk"},
	["ga"] = {en = "Irish", l = "Gaeilge"},
	["gallego"] = {en = "gallego (generated)"},
	["gallo"] = {en = "gallo (generated)"},
	["galo"] = {en = "galo (generated)"},
	["gd"] = {en = "Gaelic"},
	["gez"] = {en = "Ge'ez"},
	["gl"] = {en = "Galician", l = "Galego"},
	["glk"] = {en = "Gilaki"},
	["gmh"] = {en = "High German (Middle)"},
	["gn"] = {en = "Guarani"},
	["got"] = {en = "Gothic"},
	["gr_GR"] = {en = "Greek"},
	["grc"] = {en = "Greek (Ancient)"},
	["gsw"] = {en = "Alemannic"},
	["gu"] = {en = "Gujarati"},
	["gu_IN"] = {en = "Gujarati (India)"},
	["guc"] = {en = "Wayuu"},
	["gug"] = {en = "Guaraní (Paraguayan)"},
	["gum"] = {en = "Guambiano"},
	["guw"] = {en = "Gun"},
	["gv"] = {en = "Manx"},
	["ha"] = {en = "Hausa"},
	["haw"] = {en = "Hawaiian"},
	["he"] = {en = "Hebrew", l = "עברית"},
	["he_IL"] = {en = "Hebrew (Israel)"},
	["hi"] = {en = "Hindi", l = "हिंदी"},
	["hi_Latn"] = {en = "Hindi (latin)"},
	["hne"] = {en = "Chhattisgarhi"},
	["ho"] = {en = "Hiri Motu"},
	["hr"] = {en = "Croatian", l = "Hrvatski"},
	["hrx"] = {en = "Hunsrik"},
	["hsb"] = {en = "Upper Sorbian"},
	["ht"] = {en = "Haitian"},
	["hu"] = {en = "Hungarian", l = "Magyar"},
	["hu_ZZ"] = {en = "Hungarian"},
	["hus"] = {en = "Huastec"},
	["hy"] = {en = "Armenian", l = "Հայերեն"},
	["hz"] = {en = "Herero"},
	["ia"] = {en = "Interlingua", l = "interlingua"},
	["ia_FR"] = {en = "Interlingua"},
	["id"] = {en = "Indonesian", l = "Indonesia"},
	["ie"] = {en = "Occidental", l = "Interlingue"},
	["ig"] = {en = "Igbo"},
	["ii"] = {en = "Nuosu"},
	["ik"] = {en = "Inupiaq"},
	["io"] = {en = "Ido"},
	["is"] = {en = "Icelandic", l = "Íslenska"},
	["it"] = {en = "Italian", l = "Italiano"},
	["it_CARES"] = {en = "Italian"},
	["it_CH"] = {en = "Italian (Switzerland)"},
	["it_LAVA"] = {en = "Italian"},
	["it_V26"] = {en = "Italian"},
	["iu"] = {en = "Inuktitut"},
	["ja"] = {en = "Japanese", l = "日本語"},
	["ja_CARES"] = {en = "Japanese"},
	["ja_KANJI"] = {en = "Japanese"},
	["ja_KS"] = {en = "Japanese (Kansai)"},
	["ja_LAVA"] = {en = "Japanese"},
	["jam"] = {en = "Jamaican Patois"},
	["jbo"] = {en = "Lojban"},
	["jbo_EN"] = {en = "Lojban"},
	["jv"] = {en = "Javanese"},
	["ka"] = {en = "Georgian", l = "ქართული"},
	["kab"] = {en = "Kabyle", l = "Taqbaylit"},
	["kg"] = {en = "Kongo"},
	["ki"] = {en = "Gikuyu"},
	["kj"] = {en = "Kwanyama"},
	["kk"] = {en = "Kazakh", l = "Qazaq"},
	["kk_Latn"] = {en = "Kazakh (latin)"},
	["kl"] = {en = "Greenlandic"},
	["km"] = {en = "Khmer (Central)"},
	["kmr"] = {en = "Kurdish (Northern)"},
	["kn"] = {en = "Kannada", l = "ಕನ್ನಡ"},
	["ko"] = {en = "Korean", l = "한국어"},
	["ko_LAVA"] = {en = "Korean"},
	["kok"] = {en = "Konkani"},
	["kok@latin"] = {en = "Konkani"},
	["kr"] = {en = "Kanuri"},
	["krl"] = {en = "Karelian"},
	["ks"] = {en = "Kashmiri"},
	["ksh"] = {en = "Colognian", l = "Kölsch"},
	["ku"] = {en = "Kurdish"},
	["kv"] = {en = "Komi"},
	["kw"] = {en = "Cornish"},
	["ky"] = {en = "Kyrgyz"},
	["la"] = {en = "Latin"},
	["lang"] = {en = "lang (generated)"},
	["laserdenta"] = {en = "laserdenta (generated)"},
	["lb"] = {en = "Luxembourgish"},
	["lfn"] = {en = "Lingua Franca Nova"},
	["lg"] = {en = "Luganda"},
	["li"] = {en = "Limburgish"},
	["ln"] = {en = "Lingala", l = "Lingála"},
	["lo"] = {en = "Lao"},
	["locale"] = {en = "locale (generated)"},
	["lt"] = {en = "Lithuanian", l = "lietuvių"},
	["lt_CARES"] = {en = "Lithuanian"},
	["ltg"] = {en = "Latgalian"},
	["lu"] = {en = "Luba-Katanga"},
	["lv"] = {en = "Latvian", l = "Latviešu"},
	["lyra"] = {en = "lyra (generated)"},
	["lzh"] = {en = "Chinese (Literary)"},
	["mai"] = {en = "Maithili"},
	["mcc234"] = {en = "mcc234 (generated)"},
	["mcc235"] = {en = "mcc235 (generated)"},
	["messages"] = {en = "messages (generated)"},
	["mg"] = {en = "Malagasy"},
	["mh"] = {en = "Marshallese"},
	["mhr"] = {en = "Meadow Mari"},
	["mi"] = {en = "Maori"},
	["mia"] = {en = "Miami"},
	["microdent"] = {en = "microdent (generated)"},
	["min"] = {en = "Minangkabau"},
	["mjw"] = {en = "Karbi"},
	["mk"] = {en = "Macedonian", l = "македонски"},
	["ml"] = {en = "Malayalam", l = "മലയാളം"},
	["mm"] = {en = "mm (generated)"},
	["mn"] = {en = "Mongolian"},
	["mnc"] = {en = "Manchu"},
	["mni"] = {en = "Manipuri"},
	["mni@bengali"] = {en = "Manipuri"},
	["mnw"] = {en = "Mon"},
	["mr"] = {en = "Marathi", l = "मराठी"},
	["ms"] = {en = "Malay", l = "Bahasa Melayu"},
	["ms_Arab"] = {en = "Malay (Jawi)"},
	["mt"] = {en = "Maltese"},
	["my"] = {en = "Burmese", l = "မြန်မာ"},
	["my@Zawgyi"] = {en = "Burmese (Zawgyi)"},
	["na"] = {en = "Nauru"},
	["nah"] = {en = "Nahuatl"},
	["nan"] = {en = "Chinese (Min Nan)"},
	["nap"] = {en = "Neapolitan"},
	["nb_NO"] = {en = "Norwegian Bokmål"},
	["nb_NO-V26"] = {en = "Norwegian Bokmål"},
	["nd"] = {en = "Ndebele (Northern)"},
	["nds"] = {en = "German (Low)"},
	["ne"] = {en = "Nepali"},
	["ne_LATN@ne"] = {en = "Nepali"},
	["ng"] = {en = "Ndonga"},
	["night"] = {en = "night (generated)"},
	["nl"] = {en = "Dutch", l = "Nederlands"},
	["nl@informal"] = {en = "Dutch (informal)"},
	["nl_BE"] = {en = "Dutch (Belgium)"},
	["nl_CARES"] = {en = "Dutch"},
	["nl_LAVA"] = {en = "Dutch"},
	["nl_TND"] = {en = "Dutch"},
	["nn"] = {en = "Norwegian Nynorsk", l = "Norsk (nynorsk)"},
	["nqo"] = {en = "N’Ko"},
	["nr"] = {en = "Ndebele (Southern)"},
	["nso"] = {en = "Pedi"},
	["nv"] = {en = "Navaho"},
	["ny"] = {en = "Nyanja"},
	["oc"] = {en = "Occitan", l = "occitan"},
	["oj"] = {en = "Ojibwe"},
	["om"] = {en = "Oromo"},
	["openstore_web_CA"] = {en = "openstore_web_CA (generated)"},
	["opera"] = {en = "opera (generated)"},
	["or"] = {en = "Odia", l = "ଓଡ଼ିଆ"},
	["os"] = {en = "Ossetian"},
	["ota"] = {en = "Turkish (Ottoman)"},
	["otk"] = {en = "Kokturk"},
	["pa"] = {en = "Punjabi", l = "ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ)"},
	["pa_PK"] = {en = "Punjabi (Pakistan)"},
	["pam"] = {en = "Pampanga"},
	["pap"] = {en = "Papiamento"},
	["pbb"] = {en = "Páez"},
	["peo"] = {en = "Persian (Old)"},
	["pi"] = {en = "Pali"},
	["pl"] = {en = "Polish", l = "polski"},
	["pl@informal"] = {en = "Polish (informal)"},
	["pl_CARES"] = {en = "Polish"},
	["pl_PL@rude"] = {en = "Polish"},
	["pl_V26"] = {en = "Polish"},
	["pms"] = {en = "Piemontese"},
	["pon"] = {en = "Pohnpeian"},
	["prg"] = {en = "Prussian"},
	["ps"] = {en = "Pashto", l = "پښتو"},
	["pt"] = {en = "Portuguese", l = "Português"},
	["pt_AO"] = {en = "Portuguese (Angola)"},
	["pt_BR"] = {en = "Portuguese (Brazil)"},
	["pt_BR-V26"] = {en = "Portuguese"},
	["pt_CARES"] = {en = "Portuguese"},
	["pt_LAVA"] = {en = "Portuguese"},
	["pt_PT"] = {en = "Portuguese (Portugal)"},
	["pt_PT-V26"] = {en = "Portuguese"},
	["qt"] = {en = "qt (generated)"},
	["qtq_LATN"] = {en = "qtq_LATN (generated)"},
	["qu"] = {en = "Quechua"},
	["qu_EC"] = {en = "Quechua (Ecuador)"},
	["quc"] = {en = "K'iche'"},
	["qya"] = {en = "Quenya"},
	["rcf"] = {en = "Réunion Creole"},
	["readme_CZ"] = {en = "readme_CZ (generated)"},
	["readme_FA"] = {en = "readme_FA (generated)"},
	["readme_zh_CN"] = {en = "readme_zh_CN (generated)"},
	["rm"] = {en = "Romansh"},
	["rn"] = {en = "Rundi"},
	["ro"] = {en = "Romanian", l = "Română"},
	["ro_MD"] = {en = "Moldavian"},
	["ro_V26"] = {en = "Romanian"},
	["rom"] = {en = "Romany"},
	["round"] = {en = "round (generated)"},
	["ru"] = {en = "Russian", l = "Русский"},
	["ru@informal"] = {en = "Russian (informal)"},
	["ru_CARES"] = {en = "Russian"},
	["ru_CH"] = {en = "Russian"},
	["ru_DWOS"] = {en = "Russian"},
	["ru_OLD"] = {en = "Russian"},
	["ru_SOV"] = {en = "Russian"},
	["ru_UA"] = {en = "Russian (Ukraine)"},
	["rue"] = {en = "Rusyn"},
	["rup"] = {en = "Macedo-Romanian"},
	["rw"] = {en = "Kinyarwanda"},
	["ryu"] = {en = "ryu (generated)"},
	["sa"] = {en = "Sanskrit"},
	["sah"] = {en = "Yakut"},
	["sai"] = {en = "South American Indian (Other)"},
	["sat"] = {en = "Santali"},
	["sc"] = {en = "Sardinian", l = "Sardu"},
	["scanlab"] = {en = "scanlab (generated)"},
	["scn"] = {en = "Sicilian"},
	["sco"] = {en = "Scots"},
	["sd"] = {en = "Sindhi"},
	["sdh"] = {en = "Kurdish (Southern)"},
	["se"] = {en = "Sami (Northern)"},
	["sg"] = {en = "Sango"},
	["sgn"] = {en = "Sign Languages"},
	["sh_HR"] = {en = "Serbian (latin)"},
	["shera"] = {en = "shera (generated)"},
	["shn"] = {en = "Shan"},
	["si"] = {en = "Sinhala", l = "සිංහල"},
	["signatures"] = {en = "signatures (generated)"},
	["sk"] = {en = "Slovak", l = "Slovenčina"},
	["sk_CS@cz"] = {en = "Slovak"},
	["sk_HU@hu"] = {en = "Slovak"},
	["skr"] = {en = "Saraiki", l = "سرائیکی"},
	["sl"] = {en = "Slovenian", l = "slovenščina"},
	["sm"] = {en = "Samoan"},
	["sma"] = {en = "Sami (Southern)"},
	["sn"] = {en = "Shona"},
	["so"] = {en = "Somali"},
	["son"] = {en = "Songhai"},
	["sq"] = {en = "Albanian", l = "Shqip"},
	["sr"] = {en = "Serbian", l = "српски"},
	["sr_CYR"] = {en = "Serbian"},
	["sr_Cyrl"] = {en = "Serbian (cyrillic)"},
	["sr_LAT"] = {en = "Serbian"},
	["sr_LATN@me"] = {en = "Serbian (latin)"},
	["sr_Latn"] = {en = "Serbian (latin)"},
	["sr_SP"] = {en = "Serbian"},
	["ss"] = {en = "Swati"},
	["st"] = {en = "Sotho (Southern)"},
	["straumann"] = {en = "straumann (generated)"},
	["su"] = {en = "Sundanese"},
	["suk"] = {en = "Sukuma"},
	["sv"] = {en = "Swedish", l = "Svenska"},
	["sw"] = {en = "Swahili", l = "Kiswahili"},
	["sw600dp_PORT"] = {en = "sw600dp_PORT (generated)"},
	["sw720dp"] = {en = "sw720dp (generated)"},
	["sw_KE"] = {en = "Swahili"},
	["synthetic"] = {en = "synthetic (generated)"},
	["szl"] = {en = "Silesian"},
	["ta"] = {en = "Tamil", l = "தமிழ்"},
	["ta_LK"] = {en = "Tamil (Sri Lanka)"},
	["te"] = {en = "Telugu", l = "తెలుగు"},
	["template"] = {en = "template (generated)"},
	["test"] = {en = "test (generated)"},
	["tet"] = {en = "Tetum"},
	["tg"] = {en = "Tajik"},
	["th"] = {en = "Thai", l = "ไทย"},
	["ti"] = {en = "Tigrinya"},
	["tig"] = {en = "Tigre"},
	["tk"] = {en = "Turkmen"},
	["tl"] = {en = "Tagalog"},
	["tlh"] = {en = "Klingon"},
	["tlh_AA"] = {en = "Klingon"},
	["tli"] = {en = "Tlingit"},
	["tn"] = {en = "Tswana"},
	["to"] = {en = "Tongan"},
	["tok"] = {en = "Toki Pona", l = "Toki Pona"},
	["tr"] = {en = "Turkish", l = "Türkçe"},
	["tr_V26"] = {en = "Turkish"},
	["translation"] = {en = "translation (generated)"},
	["trv"] = {en = "Taroko"},
	["ts"] = {en = "Tsonga"},
	["tt"] = {en = "Tatar", l = "Татарча"},
	["tt@iqtelif"] = {en = "Tatar (IQTElif)"},
	["tum"] = {en = "Tumbuka"},
	["tw"] = {en = "Twi"},
	["ty"] = {en = "Tahitian"},
	["tzj"] = {en = "Tz'utujil"},
	["tzm"] = {en = "Tamazight (Central Atlas)"},
	["udm"] = {en = "Udmurt"},
	["ug"] = {en = "Uyghur", l = "ئۇيغۇرچە"},
	["ug@arab"] = {en = "Uyghur"},
	["uk"] = {en = "Ukrainian", l = "українська"},
	["ukr_UA"] = {en = "Ukrainian"},
	["und"] = {en = "Undetermined"},
	["untranslated"] = {en = "untranslated (generated)"},
	["ur"] = {en = "Urdu"},
	["ur_IN"] = {en = "Urdu (India)"},
	["ur_PK"] = {en = "Urdu (Pakistan)"},
	["uroc"] = {en = "uroc (generated)"},
	["uz"] = {en = "Uzbek", l = "o‘zbek"},
	["uz@cyrillic"] = {en = "Uzbek"},
	["uz_CYRL"] = {en = "Uzbek"},
	["uz_Latn"] = {en = "Uzbek (latin)"},
	["v20"] = {en = "v20 (generated)"},
	["v28"] = {en = "v28 (generated)"},
	["val"] = {en = "val (generated)"},
	["ve"] = {en = "Venda"},
	["vec"] = {en = "Venetian"},
	["vi"] = {en = "Vietnamese", l = "Tiếng Việt"},
	["vls"] = {en = "Flemish (West)"},
	["vo"] = {en = "Volapük"},
	["wa"] = {en = "Walloon"},
	["wae"] = {en = "German (Walser)"},
	["wal"] = {en = "Wolaytta"},
	["wo"] = {en = "Wolof"},
	["xh"] = {en = "Xhosa"},
	["xx_XX"] = {en = "xx_XX (generated)"},
	["yi"] = {en = "Yiddish"},
	["yo"] = {en = "Yoruba"},
	["yue_HK"] = {en = "Yue"},
	["yue_Hant"] = {en = "Yue (Traditional)"},
	["za"] = {en = "Zhuang"},
	["zeno"] = {en = "zeno (generated)"},
	["zgh"] = {en = "Tamazight (Standard Moroccan)"},
	["zh_Hans"] = {en = "Chinese (Simplified)"},
	["zh_Hans_SG"] = {en = "Chinese (Simplified, Singapore)"},
	["zh_Hant"] = {en = "Chinese (Traditional)"},
	["zh_Hant_HK"] = {en = "Chinese (Traditional, Hong Kong)"},
	["zh_LATN@pinyin"] = {en = "Chinese (Simplified)"},
	["zh_LAVA"] = {en = "Chinese (Simplified)"},
	["zh_Latn"] = {en = "Chinese (Pinyin)"},
	["zh_MO"] = {en = "Chinese (Simplified)"},
	["zh_SIMPLIFIED"] = {en = "Chinese (Simplified)"},
	["zu"] = {en = "Zulu"},
	["😃"] = {en = "😃 (generated)"},
}
