movement_liquid_sink = 0
enable_dynamic_shadows = false
time_speed = 0
display_gamma = 2
enable_damage = true
time_send_interval = 60
desynchronize_mapblock_texture_animation = false
protocol_version_min = 43
